config/routes.rb
Arciplex::Application.routes.draw do
  devise_for :users, skip: [:registration]

  devise_scope :user do
    get "/logout" => "devise/sessions#destroy"
    get "/login" => "devise/sessions#new"
  end

  resources :customers
  resources :service_requests, only: [] do
    resources :notes
  end

  resources :orders, only: [] do
    resources :notes
  end

  resources :companies do
    resources :service_requests do
      member do
        patch 'received'
        patch 'complete'
        get 'approve'
      end
    end

    match 'service_requests/:email_hash_id/print', to: 'service_requests#print', via: :get, as: 'print_service_request'

    resources :orders do
      member do
        patch 'received'
        patch 'complete'
      end
    end
  end

  namespace :admin do
    get '', to: 'dashboard#index', as: '/'
    resources :users
  end

  resource :user, only: [:edit] do
    collection do
      patch 'update_password'
    end
  end

  resources :pages, only: [:show]
  resources :contacts, only: :create

  match "1327D73CAFF529BF483CCA3A87E33B1B.txt", to: 'home#ssl', via: :get

  mount ServiceRequests::API => '/api'

  root to: "home#index"
end

app/views/shared/_breadcrumbs.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="col-md-2">
        <ol class="breadcrumb">
          <li><%= fa_icon "home"  %> Home</li>
        </ol>
      </div>
      
      <div class="col-md-9 col-md-offset-1">
        <%= page_heading t("#{params[:controller].underscore}.title") %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_common_links.html.erb
<li><%= link_to "Change Password", "#", data: { toggle: "modal", target: "#user-#{current_user.id}" } %></li>
<li><%= link_to "Logout", logout_path %></li>

app/views/shared/_customer_information_form.html.erb
<%= form_for [@company, object], remote: true, html: { role: "form", class: "form-horizontal", id: "change-shipping-info" } do |f| %>
  <div class="modal-body">
    <% if object.respond_to?(:customer) %>
      <%= f.fields_for :customer do |customer| %>
        <%= render partial: 'customers/form', locals: {f: customer} %>
      <% end %>
    <% end %>
  </div>

  <div class="modal-footer">
    <%= f.submit "Submit", class: "btn btn-primary" %>
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
  </div>
<% end %>

app/views/shared/_dropdown_menu.html.erb
<% hsh = {} %>
<% hsh[:company_id] = params[:company_id] %>
<% status_arr = ["All", "Pending", "Opened", "Closed"] %>

<%  if current_company.has_api_access? && path.include?("service_requests") %>
  <% status_arr.insert(1, "Pre-Approval") %>
<% end %>

<ul class="dropdown-menu">
  <% status_arr.each do |state| %>
    <% hsh.merge!(status: state.underscore) unless state == "All" %>
    <li><%= link_to convert_opened_to_open(state, upcase: true), send(path, hsh) %></li>
  <% end %>
</ul>

app/views/shared/_errors.html.erb
<div class="alert alert-danger">
  <p><%= object.errors.full_messages.to_sentence %></p>
</div>

app/views/shared/_footer.html.erb
<% if current_user %>
  <!-- Modal -->
  <div class="modal fade" id="user-<%= current_user.id %>" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title" id="myModalLabel">Change Your Password</h4>
        </div>

        <div class="modal-body">
          <%= render 'users/form' %>
        </div>
      </div>
    </div>
  </div>
<% end %>

</body>
</html>

app/views/shared/_header.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Arciplex</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>

  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
  <![endif]-->

  <%= csrf_meta_tags %>
</head>
<body class="<%= :'signed-in' if user_signed_in? %> <%= params[:controller].sub('admin/', '').sub('/', '-') %> <%= current_company.name.downcase if current_company %>">

  <%= render 'shared/nav' %>

app/views/shared/_nav.html.erb
<div class="navbar navbar-fixed-top" role="navigation">
  <div class="container">
    <a class="navbar-brand" href="<%= root_path %>" id="<%= current_user.try(:company_name).try(:downcase) || 'arciplex' %>"></a>
    <% if user_signed_in? %>
      <div class="collapse navbar-collapse">

        <ul class="nav navbar-nav navbar-right">
          <% if can?(:create, User) %>
            <li><%= link_to "Users", admin_users_path unless params[:company_id].present? %></li>
          <% end %>
          <% if params[:company_id].present? %>
            <% if can?(:read, ServiceRequest) %>
              <li class="dropdown">
                <%= link_to company_service_requests_path(params[:company_id]), class: "dropdown-toggle", data: { toggle: "dropdown" } do %>
                  Service Requests <span class="caret"></span>
                <% end %>

                <%= render 'shared/dropdown_menu', path: 'company_service_requests_path' %>
              </li>
            <% end %>

            <% if can?(:create, Order) && current_company.can_make_orders? %>
              <li class="dropdown">
                <%= link_to company_orders_path(params[:company_id]), class: "dropdown-toggle", data: { toggle: "dropdown" } do %>
                  Orders <span class="caret"></span>
                <% end %>

                <%= render 'shared/dropdown_menu', path: 'company_orders_path' %>
              </li>
            <% end %>
          <% end %>

          <%= render 'shared/common_links' %>

        </ul>

      </div>
    <% end %>
  </div>
</div>

app/views/shared/_page_title_and_crumbs.html.erb
<div class="container" id="breadcrumbs">
  <div class="row">
    <div class="col-md-12">
      <div class="col-md-2" id="signed-in-info">
        <ol class="breadcrumb">
          <li>
            <% if current_user.companies.many? %>
              <%= link_to admin_path do %>
                <%= fa_icon "home"  %> Home
              <% end %>
            <% else %>
              <%= link_to company_service_requests_path do %>
                <%= fa_icon "home"  %> Home
              <% end %>
            <% end %>
          </li>
          <li>
            <%= mail_to "mrfixit@arciplex.com" do %>
              <%= fa_icon "support" %> Help
            <% end %>
          </li>
        </ol>
        <span>Welcome, <%= current_user.full_name %></span>

        <% if current_company && current_company.show_user_guides? %>
          <%= render 'shared/user_guides', company_name: current_company.name, controller: params[:controller] %>
        <% end %>

        <% if params[:company_id] %>
          <p class="company-logo"><%= display_logo(params[:company_id]) %></p>
        <% end %>
      </div>

      <div class="col-md-9 col-md-offset-1">
        <%= content_for?(:page_title) ? content_tag(:h1, content_for(:page_title)) : "Page Title" %>

        <%= js flash_messages %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_search_form.html.erb
<form action="<%= url %>" method="get" id="search-form">
  <div class="form-group">
    <label for="search">Search</label>
    <input type="text" name="search" id="search" class="form-control" placeholder="Search <%= placeholder %>" />
  </div>

  <div class="form-group">
    <button type="submit" class="btn btn-success" id="search-submit-btn">Submit</button>
  </div>
</form>

app/views/shared/_user_guides.html.erb
<% if can?(:read, :user_guides) %>
  <p><%= user_guide_link(company_name, controller) %></p>
<% end %>