config/routes.rb
Arciplex::Application.routes.draw do
  devise_for :users, skip: [:registration]

  devise_scope :user do
    get "/logout" => "devise/sessions#destroy"
    get "/login" => "devise/sessions#new"
  end

  resources :customers
  resources :service_requests, only: [] do
    resources :notes
  end

  resources :orders, only: [] do
    resources :notes
  end

  resources :companies do
    resources :service_requests do
      member do
        patch 'received'
        patch 'complete'
        get 'approve'
      end
    end

    match 'service_requests/:email_hash_id/print', to: 'service_requests#print', via: :get, as: 'print_service_request'

    resources :orders do
      member do
        patch 'received'
        patch 'complete'
      end
    end
  end

  namespace :admin do
    get '', to: 'dashboard#index', as: '/'
    resources :users
  end

  resource :user, only: [:edit] do
    collection do
      patch 'update_password'
    end
  end

  resources :pages, only: [:show]
  resources :contacts, only: :create

  match "1327D73CAFF529BF483CCA3A87E33B1B.txt", to: 'home#ssl', via: :get

  mount ServiceRequests::API => '/api'

  root to: "home#index"
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  belongs_to :user
  belongs_to :customer
  belongs_to :company
  has_one :shipping_information, dependent: :destroy

  accepts_nested_attributes_for :shipping_information

  delegate :address, :address2, :city, :state, :country, :zip_code, :address_type, to: :shipping_information

  validates_presence_of :first_name, :contact_email, :phone_number

  scope :in_company, ->(company_id) { where company_id: company_id }

  def full_name
    "#{first_name} #{last_name}".squish
  end

  def state_city_zip
    "#{shipping_information.try(:city)}, #{shipping_information.try(:state)} #{shipping_information.try(:zip_code)}".squish
  end
  
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :load_customer
  skip_before_filter :load_customer, only: [:create, :update]
  
  respond_to :html, :js
  
  def index
    @customers = Customer.in_company(current_user.company_id).paginate(page: params[:page])
  end
  
  def create
    @customer = current_user.customers.new(customer_params)
    @customer.company_id = current_user.company.id
    
    if @customer.save
      redirect_to customers_path, notice: "Customer created successfully!"
    else
      render :new
    end
  end
  
  def update
    @customer = current_user.customers.find params[:id]
    
    if @customer.update_attributes customer_params
      flash[:notice] = "#{@customer.full_name} updated successfully!"
      redirect_to customer_path @customer
    else
      render :edit
    end
  end
  
  def destroy
    if @customer.destroy
      redirect_to customers_path, notice: "Customer has been removed!"
    else
      redirect_to customers_path, notice: "An error occurred. Please try again!"
    end
  end
  
  private
    def load_customer
      if params[:id]
        @customer = Customer.in_company(current_user.company_id).find(params[:id])
      else
        @customer = Customer.new
        @customer.build_shipping_information
      end
    end
  
    def customer_params
      params.require(:customer).permit(:prefix, :first_name, :last_name, :contact_email, :phone_number, 
                                      shipping_information_attributes: [:id, :address, :address2, :city, :state, :zip_code, :country, :address_type])
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
  
  def address_type_options
    [
      ['Residential', 'Residential'],
      ['Business', 'Business']
    ]
  end
  
end

app/views/customers/_customer.html.erb
<tr data-customer-id="<%= customer.id %>">
  <td><%= customer.full_name %></td>
  <td><%= customer.contact_email %></td>
  <td><%= customer.phone_number %></td>
  <td>
      <%= link_to "View", customer_path(customer), class: "btn-sm btn-warning" %> 
      <%= link_to "Edit", edit_customer_path(customer), class: "btn-sm btn-warning" %>
      <%= link_to "Remove", customer_path(customer), method: :delete, class: "btn-sm btn-warning", data: { confirm: "Are you sure?" } %>
  </td>
</tr>

app/views/customers/_form.html.erb
<div class="form-group">
  <%= f.label :prefix, class: "col-md-2 control-label" %>
  <div class="col-md-8">
    <%= f.text_field :prefix, class: "form-control" %>
  </div>
</div>

<div class="form-group">
  <%= f.label :first_name, class: "col-md-2 control-label" %>
  <div class="col-md-8">
    <%= f.text_field :first_name, class: "form-control" %>
  </div>
</div>

<div class="form-group">
  <%= f.label :last_name, class: "col-md-2 control-label" %>
  <div class="col-md-8">
    <%= f.text_field :last_name, class: "form-control" %>
  </div>
</div>

<div class="form-group">
  <%= f.label :contact_email, class: "col-md-2 control-label" %>
  <div class="col-md-8">
    <%= f.email_field :contact_email, class: "form-control" %>
  </div>
</div>

<div class="form-group">
  <%= f.label :phone_number, "Telephone", class: "col-md-2 control-label" %>
  <div class="col-md-8">
    <%= f.text_field :phone_number, class: "form-control" %>
  </div>
</div>

<%= f.fields_for :shipping_information, f.object.shipping_information || f.object.build_shipping_information do |sh| %>

  <div class="form-group">
    <%= sh.label :company_name, class: "col-md-2 control-label" %>
    <div class="col-md-8">
      <%= sh.text_field :company_name, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= sh.label :address, class: "col-md-2 control-label" %>
    <div class="col-md-8">
      <%= sh.text_field :address, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= sh.label :address2, class: "col-md-2 control-label" %>
    <div class="col-md-8">
      <%= sh.text_field :address2, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= sh.label :city, class: "col-md-2 control-label" %>
    <div class="col-md-8">
      <%= sh.text_field :city, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= sh.label :state, class: "col-md-2 control-label" %>
    <div class="col-md-8">
      <%= sh.text_field :state, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= sh.label :zip_code, class: "col-md-2 control-label" %>
    <div class="col-md-8">
      <%= sh.text_field :zip_code, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= sh.label :country, class: "col-md-2 control-label" %>
    <div class="col-md-8">
      <%= sh.text_field :country, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= sh.label :address_type, class: "col-md-2 control-label" %>
    <div class="col-md-8">
      <%= sh.select :address_type, address_type_options, class: "form-control" %>
    </div>
  </div>

<% end %>

app/views/customers/edit.html.erb
<% content_for :page_title do %>
  <h2>You are editing <%= @customer.full_name %></h2>
<% end %>

<div class="row">
  
  <div class="col-md-9 col-md-offset-3">
    <p>Use the form below to edit <%= @customer.full_name %></p>
    
    <%= render 'form' %>
  </div>
  
</div>

app/views/customers/index.html.erb
<% content_for :page_title do %>
  <h2>Customers</h2>
<% end %>

<div class="row">
  
  <div class="col-md-9 col-md-offset-3">
    <% if @customers.empty? %>
      <%= link_to "Create New Customer", new_customer_path, class: "btn btn-primary" %>
    <% else %>
      <%= link_to "Create New Customer", new_customer_path, class: "btn btn-primary pull-right" %>
      <p>Your current Customers</p>
      
      <table class="table table-striped table-condensed" id="customer-table">
        <tr>
          <td>Name</td>
          <td>Email</td>
          <td>Phone Number</td>
          <td>Actions</td>
        </tr>
        <%= render @customers %>
      </table>
      
      <%= will_paginate @customers, renderer: BootstrapPagination::Rails %>
      
    <% end %>
  </div>
  
</div>

app/views/customers/new.html.erb
<% content_for :page_title do %>
  <h2>New Customer</h2>
<% end %>


<div class="row">
  
  <div class="col-md-9 col-md-offset-3">
    <p>Use the form below to enter in a new customer</p>
    
    <%= render 'form' %>
  </div>
  
</div>

app/views/customers/show.html.erb
<% content_for :page_title do %>
  <h2>You are viewing <%= @customer.full_name %></h2>
<% end %>


<div class="row">
  
  <div class="col-md-9 col-md-offset-3">
    <table class="table table-condensed table-hover">
      <tr>
        <td>Prefix</td>
        <td><%= @customer.prefix %></td>
      </tr>
      <tr>
        <td>First Name</td>
        <td><%= @customer.first_name %></td>
      </tr>
      <tr>
        <td>Last Name</td>
        <td><%= @customer.last_name %></td>
      </tr>
      <tr>
        <td>Email</td>
        <td><%= @customer.contact_email %></td>
      </tr>
      <tr>
        <td>Phone Number</td>
        <td><%= @customer.phone_number %></td>
      </tr>
      <tr>
        <td>Phone Number</td>
        <td><%= @customer.phone_number %></td>
      </tr>
      <tr>
        <td>Address</td>
        <td><%= @customer.address %></td>
      </tr>
      <tr>
        <td>Address 2</td>
        <td><%= @customer.address2 %></td>
      </tr>
      <tr>
        <td>City</td>
        <td><%= @customer.city %></td>
      </tr>
      <tr>
        <td>State</td>
        <td><%= @customer.state %></td>
      </tr>
      <tr>
        <td>Zip Code</td>
        <td><%= @customer.zip_code %></td>
      </tr>
      <tr>
        <td>Country</td>
        <td><%= @customer.country %></td>
      </tr>
      <tr>
        <td>Address Type</td>
        <td><%= @customer.address_type %></td>
      </tr>
    </table>
  </div>
  
</div>