config/routes.rb
Arciplex::Application.routes.draw do
  devise_for :users, skip: [:registration]

  devise_scope :user do
    get "/logout" => "devise/sessions#destroy"
    get "/login" => "devise/sessions#new"
  end

  resources :customers
  resources :service_requests, only: [] do
    resources :notes
  end

  resources :orders, only: [] do
    resources :notes
  end

  resources :companies do
    resources :service_requests do
      member do
        patch 'received'
        patch 'complete'
        get 'approve'
      end
    end

    match 'service_requests/:email_hash_id/print', to: 'service_requests#print', via: :get, as: 'print_service_request'

    resources :orders do
      member do
        patch 'received'
        patch 'complete'
      end
    end
  end

  namespace :admin do
    get '', to: 'dashboard#index', as: '/'
    resources :users
  end

  resource :user, only: [:edit] do
    collection do
      patch 'update_password'
    end
  end

  resources :pages, only: [:show]
  resources :contacts, only: :create

  match "1327D73CAFF529BF483CCA3A87E33B1B.txt", to: 'home#ssl', via: :get

  mount ServiceRequests::API => '/api'

  root to: "home#index"
end

app/models/user.rb
class User < ActiveRecord::Base
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    EMAIL_REGEX = /\b[A-Z0-9._%a-z\-]+@(?:[A-Z0-9a-z\-]+\.)+[A-Za-z]{2,4}\z/

    ROLES = %w(admin client_innovator client_innovator_limited)

    attr_accessor :temp_password

    has_many :company_users
    has_many :companies, through: :company_users
    has_many :customers
    has_many :service_requests
    has_many :notes
    has_many :orders
    has_many :permissions

    accepts_nested_attributes_for :companies, :permissions

    before_create :generate_temp_password

    def full_name
        "#{first_name} #{last_name}".squish
    end

    def save_and_notify
        save && notify
        true
    end

    def admin?
        role.eql? "admin"
    end

    def self.admin_and_who_receive_communication
        where(role: 'admin', receives_communication: true)
    end

    def notify
        UserMailerWorker.perform_async(self.id, self.temp_password)
    end

    private
        def generate_temp_password
            pwd = Devise.friendly_token
            self.temp_password = pwd
            self.password = pwd
            self.password_confirmation = pwd
        end

    protected
        def password_required?
            false
        end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_filter :authenticate_user!

  respond_to :js, :html

  def index
    @users = User.all.paginate(page: params[:page])

    respond_with @users
  end

  def show
    @user = User.find(params[:id])

    respond_with @user
  end

  def new
    @user = User.new
    @companies = Company.all

    respond_with @user
  end

  def create
    @user = User.new(user_params)

    if @user.save_and_notify
      redirect_to admin_user_path(@user), notice: "User created!"
    else
      @companies = Company.all
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
    @companies = Company.all

    respond_with @user
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(user_params)
      redirect_to admin_user_path(@user), notice: "User Updated!"
    else
      @companies = Company.all
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_path, notice: "User Removed"
  end

  private
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :role, {:company_ids => []}, :id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authenticate_user!

  respond_to :js

  def update_password
    @user = User.find(current_user.id)

    if @user.update(user_params)
      sign_in @user, bypass: true
      redirect_to after_sign_in_path_for(@user), notice: "Password Updated!"
    else
      redirect_to after_sign_in_path_for(@user), notice: "#{@user.errors.full_messages.to_sentence}"
    end
  end

  private
    def user_params
      params.require(:user).permit(:password, :password_confirmation)
    end

end

app/views/admin/users/_form.html.erb
<%= form_for [:admin, @user], html: { role: "form", class: "form-horizontal" } do |f| %>
    <%= render 'shared/errors', object: @user if @user.errors.any? %>

    <div class="form-group">
        <%= f.label :first_name, class: "col-md-4 control-label" %>
        <div class="col-md-5">
            <%= f.text_field :first_name, class: "form-control" %>
        </div>
    </div>

    <div class="form-group">
        <%= f.label :last_name, class: "col-md-4 control-label" %>
        <div class="col-md-5">
            <%= f.text_field :last_name, class: "form-control" %>
        </div>
    </div>

    <div class="form-group">
        <%= f.label :email, class: "col-md-4 control-label" %>
        <div class="col-md-5">
            <%= f.email_field :email, class: "form-control" %>
        </div>
    </div>

    <div class="form-group">
        <%= f.label :role, class: "col-md-4 control-label" %>
        <div class="col-md-5">
            <%= f.select :role, User::ROLES.map { |r| [r.humanize, r] }, class: "form-control", id: nil, prompt: true %>
        </div>
    </div>

    <div class="form-group">
        <%= f.label :companies, class: "col-md-4 control-label" %>
        <div class="col-md-5">
            <%= f.collection_select :company_ids, @companies, :id, :name, {prompt: "Please select"}, {multiple: true} %>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-10">
            <%= f.submit "Submit", class: "btn btn-success", data: { disable_with: "Processing..." } %>
        </div>
    </div>
<% end %>

app/views/admin/users/_user.html.erb
<tr data-id="<%= user.id %>">
  <td><%= user.full_name.presence || "N/A" %></td>
  <td><%= user.email %></td>
  <td class="actions">
    <%= link_to admin_user_path(user) do  %>
      <%= content_tag(:i, "", class: "glyphicon glyphicon-search") -%>
    <% end %>
    <%= link_to edit_admin_user_path(user) do %>
      <%= content_tag(:i, "", class: "glyphicon glyphicon-pencil") -%>
    <% end %>
    <%= link_to admin_user_path(user), method: :delete,
        data: { confirm: "Are you sure?" } do %>
        <%= content_tag(:i, "", class: "glyphicon glyphicon-remove") -%>
    <% end %>
  </td>
</tr>

app/views/admin/users/edit.html.erb
<% content_for :page_title do %>
  <h2>Editing User <%= @user.full_name %></h2>
<% end %>

<div class="row">

  <div class="col-md-9 col-md-offset-3">
    <%= render 'form' %>
  </div>

</div>

app/views/admin/users/index.html.erb
<% content_for :page_title do %>
  <h2>Users</h2>
  <p>All Users</p>
<% end %>

<div class="row">

  <div class="col-md-9 col-md-offset-3">
        <%= link_to "Create New User", new_admin_user_path, class: "btn btn-primary #{:'pull-right' unless @users.empty?}" %>

      <% unless @users.empty? %>

        <p>Current Users</p>

        <table class="table table-striped table-condensed" id="customer-table">
          <tr>
            <td>Name</td>
            <td>Email</td>
            <td>Actions</td>
          </tr>
          <%= render @users %>
        </table>

        <%= will_paginate @users, renderer: BootstrapPagination::Rails %>

      <% end %>
  </div>

</div>

app/views/admin/users/new.html.erb
<% content_for :page_title do %>
  <h2>Create a new User</h2>
  <p>Use the form below to create a new user</p>
<% end %>

<div class="row">

  <div class="col-md-9 col-md-offset-3">
    <%= render 'form' %>
  </div>

</div>

app/views/admin/users/show.html.erb
<% content_for :page_title do %>
  <h2>Viewing User <%= @user.full_name %></h2>
  <%= link_to "Edit User", edit_admin_user_path(@user), class: "btn btn-primary pull-right" %>
<% end %>

<div class="row">
  <div class="col-md-9">
    <h3>Email: <%= @user.email %></h3>
    <p>Company: <%= @user.admin? ? "All" : @user.companies.collect(&:name).uniq.to_sentence %></p>
  </div>
</div>